clear
%% compile .mat files into one .csv file
load bugsScraped.mat
load tempFlowYearly.mat
load returnsSpanish.mat
load releasesSpanish.mat
load returnsIndian.mat
load returnsKanaka.mat
load returnsCapilano.mat
load WestVanEstuaries.mat
% load returnsWestVan.mat % this data is held by West Van Streamkeepers.
                          % contact John Barker; he's very helpful
    returnsWestVan = nan(1,8); % delete these three lines & uncomment above
    tReturnsWestVan = 2020;    % once you get West Van data
    fieldsReturnsWestVan = strcat("West Van ", string(1:8));


t = (min(tReturnsKanaka):2025)'; % adds time to accommodate Kanaka offset
tBugs = year(tBugs);
returnsCapSimpl = [sum(returnsCapilano(:,1:4),2), ...
    sum(returnsCapilano(:,5:6),2), returnsCapilano(:,7:end)];
fieldsReturnsCapSimpl = ["returns Cap coho", "returns Cap chinook", ...
    "returns Cap summer steelhead", "returns Cap winter steelhead", ...
    "returns Cap chum", "returns Cap pink"];  

dataA = [fitData(dataBugs, tBugs, t), ...
         fitData(dataTFYAut, tTFYAut, t), ...
         fitData(returnsSpanish, tReturnsSpanish, t), ...
         fitData(releasesSpanish, tReleasesSpanish, t), ...
         fitData(returnsIndian, tReturnsIndian, t), ...
         fitData(returnsKanaka, tReturnsKanaka, t), ...
         fitData(returnsKanaka, tReturnsKanaka+4, t), ...
         fitData(returnsCapSimpl, tReturnsCapilano, t), ...
         fitData(numWVEstuaries, tNumWVEstuaries, t), ...
         fitData(returnsWestVan, tReturnsWestVan, t)];

dataTable = array2table([t, dataA], ...
    'variablenames',["year", fieldsBugs, fieldsTFYAut, ...
    "returns Spanish chum", "releases Spanish", "returns Indian chum", ...
    "returns Kanaka chum", "returns Kanaka chum (+4 yr)", ...
    fieldsReturnsCapSimpl, "number of improved West Van estuaries", ...
    fieldsReturnsWestVan]);
writetable(dataTable,'dataFull.csv')


%% sub-functions
function out = fitData(in, tIn, tFull)
out = nan(length(tFull),size(in,2));
out(any(tFull == tIn',2),:) = in;
end





